### ISSUE TITLE
MQTT Sub sampler "Dual SSL authentication" gets auto-selected unwantedly.

### ISSUE THREAD

**Issue by Raul666** [emqtt/mqtt-jmeter#11] opened 2017-03-29 11:00 UTC
I do not need Dual SSL authentication so In my Test plan, I use SUB sampler, with only Trust Key Store(*.jks) and leave Client Ceritfication empty.
It works fine.
Now if i close the test plan and open it again, it selects the Dual SSL Authentication check box by default and due to this my response never comes and test fails.
(Note:Previous version was not having this issue.)  same issue applies to PUB sampler as well.
![image](https://cloud.githubusercontent.com/assets/16193327/24451588/c05ed0f2-147f-11e7-9000-65a8b9720426.png)

**Comment by rende2005** [comment] 2017-03-29 15:20
Hi Raul, 

If you are not using Dual SSL, which means only server certificate will be examined, you don't need to provide the Trust Key Store info in the plugin sampler. Just leave all the fields empty and you'll be good.  Plugin trusts all server certificates under this one-way authentication mode.

**Comment by Raul666** [comment] 2017-03-29 15:29
thanks Dang,
Just tested, indeed it works without giving the certificate. but its strange i tested same 2weeks ago and without certificate it was connecting.

________________________________

**Comment by Raul666** [comment] 2017-03-30 07:02
I removed the certificate and unselected the DUAL SSL check box. saved the test.
Manually running fine. now i closed the jmeter and started the Jenkins to run the Jmeter tests.

- What happens is that the check box for Dual SSL Cerification is again by default selected and it try's to Load key files. see log below:

2017/03/30 08:58:21 INFO  - net.xmeter.Util: **Configured with dual SSL, trying to load key files.** 
2017/03/30 08:58:21 ERROR - net.xmeter.samplers.SubSampler: apache-jmeter-3_enginesMQTTWS3\apache-jmeter-3.1\bin\tests (Access is denied) java.io.FileNotFoundException: apache-jmeter-3_enginesMQTTWS3\apache-jmeter-3.1\bin\tests (Access is denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at net.xmeter.Util.getContext(Util.java:84)
	at net.xmeter.samplers.SubSampler.sample(SubSampler.java:92)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:475)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:418)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:249)
	at java.lang.Thread.run(Unknown Source)

**Comment by rende2005** [comment] 2017-03-30 08:15
Please reproduce it, and save jmx file separately for each stage, so that we can investigate what triggers the settings change.  

Specifically, you may keep an closer eye on “mqtt.dual_ssl_authentication” in jmx files.

**Comment by Raul666** [comment] 2017-04-19 09:20
Im not using any authentication what so ever,
I tested on two laptops.
using same jmx file and also tried with a new jmx test script.

Before i close the jmeter gui i checked that all the checkboxes in all requests were unselected.
gui looks like this 👍 
![image](https://cloud.githubusercontent.com/assets/16193327/25172709/26fb0b14-24f2-11e7-8a05-f3fc1e331d4d.png)

But as soon as i close gui of jmeter and restart jmeter again and load the jmx test script. It auto selects the Dual checkbox.
the gui then looks like this:
![image](https://cloud.githubusercontent.com/assets/16193327/25172722/3024c78e-24f2-11e7-84fb-b36affe9a498.png)


This is the reason that i can no longer run the mqtt test scripts using our jenkins build server. This is now really a blocking issue for me as rest of the team cannot view the results of the test and i have to run test locally and not on jenkins buildserver. ,

**Comment by jinfahua** [comment] 2017-04-21 03:49
Since I cannot reproduce the problem, please help to validate following:
1) Keep the "Dual SSL authentication" unchecked, and save the script.
2) Open the jmx file with a text file editor, and find 'mqtt.dual_ssl_authentication' in the file. If it's saved correctly, the value should be **<boolProp name="mqtt.dual_ssl_authentication">false</boolProp>** . 

If the value of mqtt.dual_ssl_authentication is set to true, then it's a bug of saving script. If the value is false, then it's a problem when loading the script.

Also, please provide the OS, Java and JMeter version.

**Comment by Raul666** [comment] 2017-04-26 12:31
I did what you suggested. the value is True.
![image](https://cloud.githubusercontent.com/assets/16193327/25434539/f9137a2e-2a8c-11e7-8162-0d11ac3080f2.png)

**Comment by jinfahua** [comment] 2017-04-26 14:48
I still cannot reproduce the problem. Can you attach your jmeter.log when saving the jmx file? Also, you can provide the OS, Java and JMeter version. If it's possible, send your jmx file to my email address: jinfahua@xmeter.net

As a workaround, you can manually update the value to false, then run it in Jenkins.

**Comment by Raul666** [comment] 2017-04-27 14:32
windows 10, jmeter 3.1 r1770033, java 8 64bit, 

your workaround is right. i manually edited the notepad to run it.  do you have a skype id? I need to discuss some more thing related to service providing for mqtt testing..

**Comment by jinfahua** [comment] 2017-04-28 02:44
I don't have windows 10, but tested with Windows 7, and same JMeter, Java version. I cannot reproduce the saving script problem. 

My skype id was sent to your hotmail email, please check it.

**Comment by Raul666** [comment] 2017-04-28 11:36
didnt got any mails. mailed to you my id on rendangen@xmeter.net

**Comment by jinfahua** [comment] 2017-12-18 03:10
Cannot reproduced the problem, close the issue.

**Closed by jinfahua** 2017-12-18 03:10 UTC
Labels: Support
