### ISSUE TITLE
port out of range:-1

### ISSUE THREAD

**Issue by avana9** [emqtt/mqtt-jmeter#4] opened 2017-02-23 10:38 UTC
i am trying to publish a massage to IOT on port 8883 but detect an exception (in attach the configuration
![issue](https://cloud.githubusercontent.com/assets/25978410/23255606/906b5452-f9bc-11e6-9eff-3bcf4919e2cd.jpg)
):

1. if i use this Server Name: SIT-IOT....... the error is:
2017/02/23 11:30:11 ERROR - net.xmeter.samplers.PubSampler: **Peer disconnected java.io.EOFException: Peer disconnected**
	at org.fusesource.hawtdispatch.transport.AbstractProtocolCodec.read(AbstractProtocolCodec.java:331)
	at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:657)
	at org.fusesource.hawtdispatch.transport.SslTransport.drainInbound(SslTransport.java:244)
	at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:538)
	at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:226)
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:96)
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)

2. if i use this Server Name: ssl://SIT-IOT....... the error is:
2017/02/23 11:37:08 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(Unknown Source)
	at java.net.InetSocketAddress.<init>(Unknown Source)
	at org.fusesource.hawtdispatch.transport.TcpTransport$2.run(TcpTransport.java:416)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by jinfahua** [comment] 2017-03-07 13:55
Not necessary to add "ssl://" in 'Server name or IP", the protocol is set in the 'Protocols' dropdown box. Please make sure that the user name & password are correct.

**Comment by avana9** [comment] 2017-03-10 14:55
username and password are correct. I've followed these instructions: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support (section: Using the MQTT protocol directly) but the error is the same:
 **ERROR - net.xmeter.samplers.PubSampler: Peer disconnected java.io.EOFException: Peer disconnected**

Moreover, where can i set "ClientId"? in MQTT Pub Sampler i see only the tag "ClientId prefix". If i set this filed with my deviceId, i detect another error.

**Comment by jinfahua** [comment] 2017-03-13 04:54
Possibly it's caused by not specifying a correct clientID. Currently, only "ClientId prefix" is supported, the fullname of clientID will be generated automatically with "ClientId_prefix" + random string.  Please verify if you can use mosquitto client tools pub/sub messages (such as specify a not correct clientId will cause the same problem or not).

**Comment by god-pane** [comment] 2017-04-21 09:26
where can i set "ClientId"? in MQTT Pub Sampler i see only the tag "ClientId prefix". If i set this filed with my deviceId, i detect another error.
Do you want to update later?   the ClientId

**Comment by rende2005** [comment] 2017-04-21 12:43
Right now as mentioned in earlier comment, "ClientId" = "ClientId_prefix" + random string.

Maybe I missed something.. are you expecting the exact ClientId field that can be specified on this Pub Sampler UI?  If so, can you elaborate how ClientId is being used in your application, should it be the same as your deviceId?

We can consider an option for ClientId without random string any way.

**Comment by god-pane** [comment] 2017-04-24 08:35
yes, in my application  the same as deviceId。
![image](https://cloud.githubusercontent.com/assets/9427959/25328833/f0178dc0-290b-11e7-98e8-cc565aa4d24a.png)

**Comment by jinfahua** [comment] 2017-04-24 15:30
Please try https://github.com/emqtt/mqtt-jmeter/releases/tag/v0.92_beta.  

As in below screen, please uncheck 'add random client id suffix', and then the value of 'ClientId' will be used as client ID. 

<img width="868" alt="2017-04-24 11 01 37" src="https://cloud.githubusercontent.com/assets/8246540/25344769/b5c0a8f2-2945-11e7-8f2c-19e110d46ed1.png">

**Comment by god-pane** [comment] 2017-04-25 01:47
It's all right now， thank you

**Comment by jinfahua** [comment] 2017-04-25 03:27
OK, so close the issue and it will be released in 0.92 stable version.

**Closed by jinfahua** 2017-04-25 03:27 UTC
Labels: Support

**Comment by devendrajha** [comment] 2017-10-05 09:23
Hi i have all proper username and password but using tcp i am not able to connect please help me out

**Comment by devendrajha** [comment] 2017-10-05 09:25
![image](https://user-images.githubusercontent.com/14250152/31220146-1812d13e-a9dd-11e7-8d48-29966b791fdb.png)

**Comment by jinfahua** [comment] 2017-10-08 12:19
Maybe it's caused by MQTT version, which was discussed in the thread - https://github.com/emqtt/mqtt-jmeter/issues/21

Could you have a try for the temp fix attached in the thread?

**Comment by devendrajha** [comment] 2017-10-09 12:13
In Jmeter testing for IOT-HUB this is TCP protocol or SSL if SSL then how i will manage certificate because i don't have any certificate

**Comment by jinfahua** [comment] 2017-10-10 05:39
Maybe you should consult Azure.

**Comment by devendrajha** [comment] 2017-10-21 07:36
Here i have notice Jmeter doesn't supprot IOT-HUB because while sending multiple message using multiple thread with delay and without delay i am getting connection error as per Azure support they were saying it is try to connect with every thread science using iot hub we can connect once 

IoT Hub only supports one active MQTT connection per device. Any new MQTT connection on behalf of the same device ID causes IoT Hub to drop the existing connection.

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support


@jinfahua  please reply with you value-able feedback

**Comment by devendrajha** [comment] 2017-10-21 07:36
@jinfahua  Here one thread working properly

**Comment by jinfahua** [comment] 2017-10-23 05:45
The current design is that all iterations for the same virtual user shares one same connection. But if you have multiple virtual users, then corresponding multiple connections will be created.  But different pub & sub samplers in one thread-group DO NOT share the same connections, different samplers in same thread-group will created a separated connection.

Now we have an ongoing release that support share connection for pub/sub samplers in the same thread-group.  In real user scenario is that one client can be either pub or sub (with the same connection).

**Comment by devendrajha** [comment] 2017-10-23 06:29
Thanks jinfahua when can we aspect this new release ??

**Comment by jinfahua** [comment] 2017-10-24 07:40
The code is already in branch conn_share https://github.com/emqtt/mqtt-jmeter/tree/share_conn , you can check it out and build a binary by yourself. The new release will still take some time.
