### ISSUE TITLE
I cant create connection to my azure IoT Hub

### ISSUE THREAD

**Issue by sharvan029** [emqtt/mqtt-jmeter#23] opened 2017-12-05 18:26 UTC
Hi,
I have been trying simulate multiple devices for load testing my IoT hub ,
But iam not able to create a successful connection to IoT hub from jmeter
![connecrionsampller](https://user-images.githubusercontent.com/19427484/33623541-57219f1c-da17-11e7-9447-c1a475c9b348.png)

I am getting an error like below
![image](https://user-images.githubusercontent.com/19427484/33623579-7d0fb740-da17-11e7-9507-04146b5d83a5.png)
Could you please help to fix this issue, i haven't given "ssl://" in the Server name field also there is nothing wrong with my username and Password

**Comment by jinfahua** [comment] 2017-12-07 06:36
Hi, please try the beta JAR version in https://github.com/emqtt/mqtt-jmeter/issues/21. Maybe it's caused by the MQTT version.

**Comment by jinfahua** [comment] 2017-12-18 03:15
Duplicated problem of https://github.com/emqtt/mqtt-jmeter/issues/21,  close it.

**Closed by jinfahua** 2017-12-18 03:15 UTC
Labels: question
